### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by suratovvlad** [van-ess0/qwnPlayer#1]
There are general subtasks for backend:
- Connect to owncloud and get track list via Music App API.
- Implement hierarhial model for music library.
- Implement module for playback (use QMediaPlayer).
- Test various platforms such as Android, Sailfish, WinRT (or UWP), iOS.

**Comment by van-ess0** [comment]
![image](https://cloud.githubusercontent.com/assets/3203317/10718405/024ff42e-7b83-11e5-9150-49f1f91519ce.png)

**Comment by suratovvlad** [comment]
All subtasks were solved. There are some issues:
- Playback doesn't work on WinRT (reported to Qt: QTBUG-49237 and QTBUG-49236).
- Various platforms has various set of supported audio codecs.
